# Generated by Django 5.2.5 on 2025-08-21 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('taskid', models.BigAutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('completed', models.BooleanField()),
                ('important', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
