# Generated by Django 5.2.5 on 2025-08-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.DateField(),
        ),
    ]
